// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;

    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdiZDsmRVZz5jmgVQJ3QeihmYP1g3E-qM',
    appId: '1:537611970886:web:117ccc50c78bc3a6d2dd47',
    messagingSenderId: '537611970886',
    projectId: 'soulee-b8f07',
    authDomain: 'soulee-b8f07.firebaseapp.com',
    storageBucket: 'soulee-b8f07.firebasestorage.app',
    measurementId: 'G-FRHN215YYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrWluNrPVodxzCOXxik9e48fm30D725IA',
    appId: '1:537611970886:android:0ae1d63bd1453547d2dd47',
    messagingSenderId: '537611970886',
    projectId: 'soulee-b8f07',
    storageBucket: 'soulee-b8f07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNbA6ZgdkJrr5EEHo1pmaqoHB_U82eFEo',
    appId: '1:537611970886:ios:46d727190f67ed30d2dd47',
    messagingSenderId: '537611970886',
    projectId: 'soulee-b8f07',
    storageBucket: 'soulee-b8f07.firebasestorage.app',
    iosBundleId: 'soulee.app.souleeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNbA6ZgdkJrr5EEHo1pmaqoHB_U82eFEo',
    appId: '1:537611970886:ios:46d727190f67ed30d2dd47',
    messagingSenderId: '537611970886',
    projectId: 'soulee-b8f07',
    storageBucket: 'soulee-b8f07.firebasestorage.app',
    iosBundleId: 'soulee.app.souleeProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdiZDsmRVZz5jmgVQJ3QeihmYP1g3E-qM',
    appId: '1:537611970886:web:023761d423e255acd2dd47',
    messagingSenderId: '537611970886',
    projectId: 'soulee-b8f07',
    authDomain: 'soulee-b8f07.firebaseapp.com',
    storageBucket: 'soulee-b8f07.firebasestorage.app',
    measurementId: 'G-QDYLW83FG9',
  );
}
